markdown: kramdown
exclude:
  - README.md
  - rss.xml
  - _posts/README.md
paginate: 5
paginate_path: "/blog/page:num/"
name: Dash
url: https://www.dash.org
description: Digital Cash

api: http://localhost:9090

languages: ["en", "es", "cn", "pt", "ru"]
exclude_from_localizations: ["assets"]

sass:
    style: compressed
    cache: false

gems: 
  - jekyll-paginate

collections:
  components: # style guide
    output: false
  colors: # style guide
    output: false
