markdown: kramdown
exclude: [README.md, rss.xml, _posts/README.md]
gems: [jekyll-paginate]
# paginate: 5
# paginate_path: "/blog/page:num/"
name: Dash
url: https://www.dash.org
description: Digital Cash

languages: ["en", "es"]
exclude_from_localizations: ["assets"]

sass:
    style: compressed

gems: 
  - jekyll-multiple-languages-plugin
