markdown: kramdown
exclude:
  - README.md
  - rss.xml
  - _posts/README.md
paginate: 5
paginate_path: "/blog/page:num/"
name: Dash
url: https://www.dash.org
description: Digital Cash

languages: ["en", "es"]
exclude_from_localizations: ["assets"]

sass:
    style: compressed
    cache: false
    relative_assets: true

gems: 
  - jekyll-paginate
  - jekyll-multiple-languages-plugin

collections:
  components: # style guide
    output: false
  colors: # style guide
    output: false
